name: Publish Alpha release

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: npm install

      - name: Package VS Code extension
        id: package
        uses: nhedger/package-vscode-extension@v1

      - name: Get short SHA
        id: short_sha
        run: echo "short_sha=$(echo ${{github.sha}} | cut -c -7)" >> "$GITHUB_OUTPUT"

      - name: "Publish release"
        uses: ncipollo/release-action@v1
        with:
          name: Alpha version ${{steps.short_sha.outputs.short_sha}}
          artifacts: ${{ steps.package.outputs.packagePath }}
          tag: ${{steps.short_sha.outputs.short_sha}}
          body: Alpha release of commit ${{steps.short_sha.outputs.short_sha}}
          prerelease: true
